/**
 * Builds an LLM-ready markdown context file from collected research knowledge.
 */
export function buildContextFile({ topic, papers, datasets, benchmarks, gaps }) {
  const lines = [];
  const now = new Date().toISOString().slice(0, 10);

  lines.push(`# Research Context: ${topic}`);
  lines.push(`> Generated by researchhub-cli on ${now}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Overview');
  lines.push(`This context file aggregates structured knowledge about **${topic}** from arXiv, Semantic Scholar, HuggingFace, and PapersWithCode. It is designed for use by AI agents planning experiments or literature reviews.`);
  lines.push('');

  if (papers?.length) {
    lines.push('## Key Papers');
    lines.push('');
    for (const p of papers) {
      lines.push(`### ${p.title}`);
      if (p.id) lines.push(`- **arXiv**: \`${p.id}\``);
      if (p.published) lines.push(`- **Published**: ${p.published}`);
      if (p.authors?.length) lines.push(`- **Authors**: ${p.authors.slice(0, 5).join(', ')}`);
      if (p.tldr) lines.push(`- **TL;DR**: ${p.tldr}`);
      if (p.abstract) lines.push(`- **Abstract**: ${p.abstract.slice(0, 300)}…`);
      if (p.categories?.length) lines.push(`- **Categories**: ${p.categories.join(', ')}`);
      if (p.codeUrl) lines.push(`- **Code**: ${p.codeUrl}`);
      lines.push('');
    }
  }

  if (datasets?.length) {
    lines.push('## Datasets');
    lines.push('');
    for (const d of datasets) {
      lines.push(`- **${d.name}** — ${d.url ?? ''}`);
      if (d.meta) lines.push(`  ${d.meta}`);
      if (d.tags?.length) lines.push(`  Tags: ${d.tags.join(', ')}`);
    }
    lines.push('');
  }

  if (benchmarks?.length) {
    lines.push('## Benchmarks & Tasks');
    lines.push('');
    for (const b of benchmarks) {
      lines.push(`- **${b.name}** — ${b.url ?? ''}`);
      if (b.description) lines.push(`  ${b.description.slice(0, 120)}`);
    }
    lines.push('');
  }

  if (gaps?.length) {
    lines.push('## Research Gaps');
    lines.push('');
    for (const g of gaps) {
      lines.push(`- ${g}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## Agent Instructions');
  lines.push('');
  lines.push('Use this context to:');
  lines.push(`1. Survey the current state of the art in **${topic}**`);
  lines.push('2. Identify the most relevant datasets and benchmarks for your experiment');
  lines.push('3. Locate reproducible code repositories');
  lines.push('4. Detect underexplored areas where new contributions would have high impact');

  return lines.join('\n');
}
